# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.1

MAINTAINER Jonathan Merayo <jonathan@kcouk.org>

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
