# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:5.4.1

MAINTAINER Jonathan Merayo <jonathan@kcouk.org>

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
